version: "3.9"

services:
  db:
    image: postgres:17
    container_name: cryptobot-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sniper_db
      POSTGRES_USER: sniper_user
      POSTGRES_PASSWORD: super_secret_password
    volumes:
      - cryptobot_db_data:/var/lib/postgresql/data
    networks:
      - crypto-net

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: cryptobot-app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - crypto-net
    working_dir: /app
    command: >
      bash -lc "python -m bot_scripts.db_initializer && python -u main.py --server"

networks:
  crypto-net:

volumes:
  cryptobot_db_data:
